---
- name: Get current Calm Enablement Status
  uri:
    url: "https://{{ nutanix_host }}:{{ nutanix_port }}/api/nutanix/v3/services/nucalm/status"
    method: GET
    validate_certs: "{{ validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ nutanix_api_auth }}"
  register: nutanix_calm_state

- name: Debug nutanix_calm_state
  debug:
    var: nutanix_calm_state
  when:
    - nutanix_debug

- name: Current status of Calm service(s)
  debug:
    msg: "Calm is currently in a '{{ nutanix_calm_state.json.service_enablement_status }}' state."
